/// Role of a chat message participant.
enum MessageRole {
  /// Message sent by the user.
  user,

  /// Message generated by the AI assistant.
  assistant,
}

/// A single message in an AI chat conversation.
final class ChatMessage {
  ChatMessage({
    required this.role,
    required this.text,
    DateTime? timestamp,
  }) : timestamp = timestamp ?? DateTime.now();

  ChatMessage.fromJson(Map<String, dynamic> json)
      : role = MessageRole.values.byName(json['role'] as String),
        text = json['text'] as String,
        timestamp = json['timestamp'] != null
            ? DateTime.parse(json['timestamp'] as String)
            : DateTime.now();

  /// Who sent this message.
  final MessageRole role;

  /// The message content.
  final String text;

  /// When the message was created.
  final DateTime timestamp;

  /// Create a copy with optional field overrides.
  ChatMessage copyWith({
    MessageRole? role,
    String? text,
    DateTime? timestamp,
  }) {
    return ChatMessage(
      role: role ?? this.role,
      text: text ?? this.text,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'role': role.name,
      'text': text,
      'timestamp': timestamp.toIso8601String(),
    };
  }
}
