// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPqMzV0spJD30H7RGBi3zmTEQ-G4nD1hY',
    appId: '1:330541011565:web:a1f9aefaeb5aae95e0e564',
    messagingSenderId: '330541011565',
    projectId: 'easyped-894ba',
    authDomain: 'easyped-894ba.firebaseapp.com',
    databaseURL: 'https://easyped-894ba.firebaseio.com',
    storageBucket: 'easyped-894ba.appspot.com',
    measurementId: 'G-S3J3V62ZKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIlNbQme_B7nNkat2QEDG6pQxoIlByqTY',
    appId: '1:330541011565:android:da1ff2c2561c2d9ae0e564',
    messagingSenderId: '330541011565',
    projectId: 'easyped-894ba',
    databaseURL: 'https://easyped-894ba.firebaseio.com',
    storageBucket: 'easyped-894ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1bCH8_HGVKFPpixcs4-z1Mm1L7gW8Ag',
    appId: '1:330541011565:ios:1c81f9cf001ab807e0e564',
    messagingSenderId: '330541011565',
    projectId: 'easyped-894ba',
    databaseURL: 'https://easyped-894ba.firebaseio.com',
    storageBucket: 'easyped-894ba.appspot.com',
    androidClientId:
        '330541011565-0ekek1brvq39m6c34i8en2tl2jtqj99a.apps.googleusercontent.com',
    iosClientId:
        '330541011565-lboc2bd92egf0te1dplhdvbvamhteuhd.apps.googleusercontent.com',
    iosBundleId: 'com.easymedicine',
  );
}
